# Simple workflow to host a github page based on this git project
# Add custom domain (CNAME file) to your deployment manually through "Settings>Pages>Custom Domain"
# Be aware that DNS propagation takes <= 1h, don't be alarmed by HTTPS warnings.

# https://github.com/marketplace/actions/deploy-to-github-pages

name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  deployments: write ## Github Pages

concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v3

      - name: Set Node.js 16.x ðŸ”§
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install ðŸ”§
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache

      - name: Build ðŸ”§
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      #      - name: Test ðŸ”
      #        run: |
      #          npm test

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          # creates hidden "gh-pages" branch from this to keep main clean
          folder: dist # build target of npm
